COL UESRNAME FOR A8
COL SID FOR 9999

SELECT SID,
       SERIAL#,
       USERNAME,
       STATUS,
       LOGON_TIME,
       BLOCKING_SESSION,
       BLOCKING_SESSION_STATUS
FROM  V$SESSION
WHERE USERNAME = '&USERNAME'
ORDER BY LOGON_TIME;
