COL USERNAME FOR A12
COL SERVICE_NAME FOR A16
COL RESOURCE_CONSUMER_GROUP FOR A12

SELECT SID,
       SERIAL#,
       USERNAME,
       SERVICE_NAME,
       RESOURCE_CONSUMER_GROUP
FROM V$SESSION
WHERE USERNAME = '&USERNAME';